Netflix/falcor

_includes/head.html
@jhusain (CC @ktrott @trxcllnt @sdesai @michaelbpaulson)
Turns out Facebook's debugger has, well, a bug :) This corrects the og:image tag so it's crawled properly by the crawler, instead of just crawled correctly by the debugger despite the main crawler being unable to crawl it.
Also updates og:url meta tag to point to the current page than site root, which the docs imply is the preferred usage.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/netflix/falcor/415)
=> Alter facebook share image url to avoid fb crawler issue

doc/Model.html, doc/Model.js.html
"{" before ModelResponse was caused by missing closing bracket. Added closing bracket to template and removed "{" from generated html.
=> adds missing closing bracket to template and html to correct typo

documentation/jsongraph.md
We are attempting to set todos[0].done equal to true, however midway into the narrative it changes from done to name, which causes confusion.
=> Replace name with done in references

documentation/router.md
The key was previously ignored - it was always using "name"
=> Fixed example code in multiple route paths.

README.md
> TLS has exactly one performance problem: it is not used widely enough. ([Source](https://istlsfastyet.com/))
[This example](https://github.com/Netflix/falcor#retrieving-data-from-the-virtual-json-resource) should not be influencing the use of **protocol-relative URLs**, as seen that is considered an anti-pattern nowadays. If an asset is available on HTTPS protocol, then it should be used as such, just as Google and jQuery does ([reference](https://github.com/konklone/cdns-to-https#background)).
HTTPS is ready enough.
=> Get rid of the protocol-relative URL

lib/Model.js
fixes #442
current workaround 
`falcor.Model.prototype.clone = falcor.Model.prototype._clone;`
=> fix(Model): fix batch with ._clone()

lib/ModelRoot.js, lib/index.js, lib/support/hasOwn.js, lib/walk/walk-path-map-soft-link.js, lib/walk/walk-path-map.js
Just a couple minor things I noticed could be easily refactored doing a once over
Out of curiousity, why did you decide to implement many of the support functions over using `lodash` module implementations?
=> Minor clean ups

_layouts/video-page.html
@jhusain There were previously occasional issues when youtube videos were embedded with HTTPS on some devices, but they have hopefully been sorted out, because Chrome/FF are now completely blocking non-HTTPS youtube embeds. This remedies that going forward by upgrading them all to HTTPS embeds.
=> Access all YouTube videos over HTTPS

README.md
I noticed the source url for the bitHound badge was outdated, and was causing some odd caching behaviour as well.
=> Update bitHound badge source url

.coveralls.yml
Since the project is building on Travis, Coveralls will infer the repo token automatically.
=> Delete unneeded .coveralls.yml config file

lib/response/CallResponse.js, test/falcor/call/call.spec.js
@jhusain @michaelbpaulson caught this today, does this fix look correct?
=> Fixes CallResponse to prepend the bound path to the callPath when calling the data source.

lib/support/mergeJSONGraphNode.js, performance/tests/get/get.core.perf.js, performance/tests/get/get.perf.js, test/integration/get.spec.js, test/integration/index.js, test/set/jsonGraphs/primitive.spec.js
Made a small change to merge jsonGraph node so that if the message and the cache are equivalent and nullsy then there are two outcomes, not one.  Now the merge will consider a `null` value differently than an `undefined` value.
=> merge jsonGraph with a null non sentinel value.

lib/request/SetRequest.js, lib/response/SetResponse.js, lib/set/setJSONGraphs.js, lib/set/setPathMaps.js, lib/set/setPathValues.js, test/falcor/set/set.cache-only.spec.js, test/set/jsonGraphs/expired.spec.js
@jhusain @michaelbpaulson Before, setting a PathMap on a local model where the PathMap spans existing references would build output JSON for the `optimized` paths, not the PathMap's `requested` paths. This PR fixes that.
=> Set pathMap local should perform follow-up get with requestedPaths to build proper JSON result.

lib/get/onValueType.js, test/get-core/errors.spec.js, test/get-core/references.spec.js
Found a small bug in how we are reporting errors when found at the end of a reference.
=> Error null bug

test/falcor/call/call.spec.js
Was the cause of the reduced test coverage from https://github.com/Netflix/falcor/pull/552#event-422622779
=> Removed inadvertent it.only

build/deploy-ghpages.sh, package.json
So devs don't have to remember to build and commit dists with pull requests.
=> CI will build now build *all* dists, and commits (to master)

package.json
0.1.13 was published off a branch (since master already had back-compat breaking changes).
The package.json was updated for the publish, on the branch, but needs to be reflected in master, until we publish the next bump.
=> Updating package.json to reflect latest published version

lib/errors/InvalidModelError.js, lib/errors/InvalidSourceError.js, lib/errors/MaxRetryExceededError.js
See: #586 (comment)
function.name is spec'd as read-only, and setting it, with "use strict" throws a TypeError in browser in which it's supported. In the browsers which support it, it's already "set", so we don't need to reset it.
IE seems to be the only outlier (haven't tested Edge): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Browser_compatibility
If we do need to set it for some reason, we probably need to try/catch or feature test before setting it, but not sure if we really need it set on the constructor function.
----
@michaelbpaulson @jhusain - Could you guys take a look at this.
I plan to publish 0.1.14 off the 0.x branch, once this is merged, and once I update the package.json to pull in falcor-path-syntax@0.2.3. This should take …
=> Removed [fn].name override. Causes TypeError in strict mode

.travis.yml, README.md, build/deploy-ghpages.sh
Currently the docs and Getting Started dist reflect the `0.x` branch, not `master`.
This update changes the build script to deploy gh-pages off of the 'currently released' branch (0.x for now), as opposed to `master`.
=> Updated build scripts to deploy off of current npm release

lib/support/array-flat-map.js, test/integration/call.spec.js
We ended up trying to make a get with a requestedPath = [undefined], due to a bug in arrayFlatMap which wasn't accounting for the selector filtering out values, by initializing the flatMapped array to a fixed size.
See #589
See #477#issuecomment-152336762
@michaelbpaulson @jhusain
=> Fixes exceptions on call responses with only invalidations, and no returned paths

package.json
When I require falcor and bundle with browserify, it dosen't require
in HttpDataSource, which I really want to bundle in my app.
the idea is by export the `browser.js` file so basically I can `require('falcor/browser')` instead.
=> export browser.js for browserify to require

lib/get/getCache.js, lib/support/isInternalKey.js
So instead of doing 
```
x[0] !== prefix && x !== '$size';
```
we switched it up with a more verbose check.
```
module.exports = function isInternalKey(x) {
return x === __parent ||
x === __key ||
x === __version ||
x === __prev ||
x === __next ||
x === "$size";
};
```
#601
=> getCache was still getting serializable issues

lib/get/onValueType.js, test/get-core/values.spec.js
@sdesai There is a get rule that requires if a path is missing `get` will only materialize it if there is a `_source` and `_materialized` is true, but if there already is a path that has been materialized, to report it only requires `_materialized` to be true.  I was using the former logic to generate the output, thus incorrectly generating empty output for most cases.
=> The core was not considering already materialized atoms correctly

lib/get/getCache.js, lib/get/getValueSync.js, test/falcor/bind/bind-cases.spec.js, test/falcor/get/index.js, test/get-core/edges.spec.js, test/get-core/get.cache.spec.js, test/get-core/index.js, test/getCoreRunner.js
* in legacy (removed) `_getValueSync` we were not checking the expiry of refs before following them.
* keys of undefined in the cache (after invalidate / cache clean up) were un able to be serialized.
=> Expires in getValueSync and getCache with undefined keys.

lib/deref/index.js, test/falcor/bind/bind-cases.spec.js
We were swallowing errors on preload paths, and not onNexting a successfully bound model as a result.
This PR aims to fix that (For the current 0.x deref. It's N/A for the new 1.x/master deref).
@michaelbpaulson - Could you take a quick look at this, including the unit tests (to make sure I'm testing the correct 'as designed' expectation).
=> Fixed deref completing, without onNext'ing a bound model, if the preload paths fail

lib/get/getCache.js, lib/support/isInternalKey.js, test/falcor/set/set.setCache.spec.js, test/get-core/get.cache.spec.js
I didn't get a chance to get the context around this PR from Michael in person before he stepped out on vacation: https://github.com/Netflix/falcor/pull/640/ but it seems to have regressed `model.getCache()` behavior, by allowing some internal keys to remain in the results of `model.getCache()` (e.g. refN, ref-index, etc). It seems to be a pretty conscious change, so not sure if it was intentional.
However, in the absence of this context, it seems like the desired behavior is to strip *ALL* internal keys from the cache, when returning a copy through `getCache()`.
This PR aims to fix the above regression, and also fix what seems to be a gap in the original implementation, where `$size` would still be left in the results of `getCache()` at the leaf/sentinel nodes, when cloning boxed values. …
=> Fix getCache() internal key filtering

lib/get/followReference.js, lib/get/getCache.js, lib/get/util/clone.js, lib/get/walkPath.js, lib/internal/__.js, lib/internal/absolutePath.js, lib/internal/context.js, lib/internal/head.js, lib/internal/lruPrefix.js, lib/internal/next.js, lib/internal/pathingPrefix.js, lib/internal/prev.js, lib/internal/ref-index.js, lib/internal/tail.js, lib/internal/unicodePrefix.js, lib/lru/collect.js, lib/lru/promote.js, lib/lru/splice.js, lib/support/clone.js, lib/support/isInternalKey.js, lib/support/wrapNode.js, performance/tests/deref/index.js, performance/tests/get/get.perf.js, performance/tests/lru/index.js, performance/tests/standard.js, test/CacheGenerator.js, test/get-core/get.cache.spec.js, test/get-core/values.spec.js, test/set/support/strip.js
The perf testing for this feature was tested on EC2 instances where
more accurate results could be obtained. This is showing a significant
performance improvement for the getPath algorithm. Before this change,
on EC2, a get -> merge -> get for a row representing a full lolomo
request was around 1.7 - 1.8k / s. After its 1.9 - 2.1k /s. Second,
primed cache requests went from ~29k to ~60k /s. Big performance
difference when it comes to using non-dynamic keys.
=> feat(performance): Used static keys for performance win

lib/deref/index.js, test/falcor/bind/bind-cases.spec.js
A get for the leaves can remove the current cache and cause the initial
cache to be invalid to be bound to.
=> fix(deref): The deref get can wipe out cache.

lib/response/get/checkCacheAndReport.js, test/data/LocalDataSource.js, test/falcor/error/index.js, test/falcor/get/get.dataSource-and-cache.spec.js
If the cache contains values but the requests yields only empty values, then the overall operation will simply complete.
=> 0.x fix for the materialized undefined issue.  

lib/request/GetRequestV2.js, lib/request/flushGetRequest.js, test/internal/request/GetRequest.spec.js
@jhusain the tests show all the possible outcomes now.  There was a fun race condition I had to fix when it comes to sync scheduling (ImmediateScheduler) and flushing requests.
=> DataSource's request are now disposed of

bower.json
Add support for installing Falcor via bower by adding a bower.json file to the root and defining the main file.
I have registered the fork as falcor-fix in bower so you can check behavior via
```
bower install falcor-fix#0.1.16-alpha3
```
Once you add this bower.json future release tags will become available for install via bower.
Image of what gets installed
=> Add bower support for Falcor

README.md
To make life a bit easier for developers. The project is auto-updated as well.
More info:
https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/
=> Added a production CDN link

.gitignore, build/deploy-ghpages.sh
@sdesai CC @ktrott 
Context: for the new Falcor site, the docs for each site version will be pulled in from the corresponding branch in this repo (e.g. once 1.x is master, site version 1.x will get docs from master and version 0.x from this repo's 0.x branch).
I left the jsdocs output the same because the new site can consume it as-is, and the part that commits to gh-pages directly doesn't need to be removed until the new site is launched.
This looked to me like the best place to commit the docs for the branch on a travis build, but please let me know if there's somewhere better and I'm happy to help make the changes.
Thanks!
=> Commit docs to branch on developer site build

documentation/datasources.md, documentation/jsongraph.md, documentation/model.md, documentation/paths.md, documentation/router.md, starter/getting-started.md, starter/how-does-falcor-work.md, starter/video-tutorials.md, starter/what-is-falcor.md
Besides standard English changes, I did the following:
* Replaced all "smart quotes" (`“` and `”`) with dumb quotes (`"`). In places where smart quotes were used in text, they were often wrong (two left-hand quotes or two right-hand quotes). Where they were used in code snippets, they resulted in invalid code. Jekyll converts dumb quotes to smart ones automatically anyway (ignoring code snippets).
* Replaced a bunch of instances of "JSON stringify algorithm" with "JavaScript's toString algorithm". This was already correct on the "Paths" page, but was consistently incorrect on the "JSON Graph" page. I think "JSON stringify algorithm" means `JSON.stringify` which is a way to turn a JavaScript Array or Object into a JSON string. "JavaScript's toString algorithm" is just calling `.toString` …
=> Grammar, spelling, and formatting fixes in documentation

lib/get/get.js, lib/response/get/GetResponse.js, lib/response/get/checkCacheAndReport.js, lib/response/get/getRequestCycle.js, lib/response/set/setRequestCycle.js, test/falcor/get/get.dataSource-and-cache.spec.js, test/getCoreRunner.js
Only for JSON responses, not JSONGraph. Structural sharing of unchanged subobjects.
=> Avoid mutating the previous result object during progressive get.

package.json
> Some old packages used license objects or a "licenses" property containing an array of license objects [...] Those styles are now deprecated. Instead, use SPDX expressions
https://docs.npmjs.com/files/package.json#license
=> Avoid npm no license field warning.

lib/SymbolShim.js
Recent versions of Babel will throw a TransformError in certain runtimes if any property on `Symbol` is assigned a value using dot notation, which includes React Native.  This makes sense, since you probably don't want to be assigning values on top of existing symbols anyway in environments that already support them.
This retains the same polyfilling behavior for platforms without `Symbol.for` and `Symbol.observable`, but lets Babel properly transpile.  
With the change to Falcor to support Promise shimming merged in, this is the last remaining issue needed to support React Native in 1.x. Fixes #603.
@jhusain @sdesai @ktrott
=> Fix transpilation error to support React Native

lib/set/setPathValues.js, test/set/pathValues/atom.spec.js, test/set/pathValues/primitive.spec.js
This PR fixes the issue that set would improperly short-circuit if setting beyond a reference that points to a value if that reference was already hard-linked to the value.
=> Fixes setPathValues when setting with null as last key and hard references.

lib/get/onError.js, lib/get/onValue.js, lib/get/onValueType.js, test/get-core/errors.spec.js, test/get-core/values.spec.js
Looking at get.js I suspect there may be similar problems with derefInfo and optimizedPath. Alternatively we could avoid mutating requestedPath/branchInfo/optimizedPath in walkPath.js.
=> Fix case where error is returned with wrong path

CHANGELOG.md, lib/support/mergeJSONGraphNode.js, lib/support/mergeValueOrInsertBranch.js, test/falcor/get/get.dataSource-and-cache.spec.js, test/falcor/set/set.cache-only.spec.js
This allows the errorSelector to change the $type of the leaf payload it gets in. So users can change certain errors, based on their payload, to an atom for example, if there is client side knowledge about values which can substitute for those errors.
We currently use this to fill out missing strings we request from the server, with reasonable client side defaults [ IIRC ]. We may still need to iterate on this, to see if we want to expand it's scope [ e.g. should the hook just become a general transformValueBeforeMerge hook - why does it just get errors as input. Are there use cases which warrant it getting non-errors also ].
@jhusain @lrowe @blesh @forty2
=> Allow error selector to change type

lib/Model.js, lib/response/get/getRequestCycle.js, lib/response/set/setRequestCycle.js, test/data/asyncifyDataSource.js, test/falcor/get/get.dataSource-only.spec.js
Fixing bug in which MaxRetriesExceededErrror is thrown rather than sent to observer's onError method. Previously, this error was thrown after 10 failed attempts to retrieve a value from the DataSource. Now, the number of retries can be configured by including a `maxRetries` field on the options object accepted by the Model constructor:
```js
let model = new falcor.Model({ maxRetries: 5 }); 
```
The new default value of `maxRetries` is 3 instead of 10.
=> adding maxRetries option to Model Constructor

lib/get/onValue.js, lib/get/onValueType.js, test/falcor/get/get.dataSource-and-cache.spec.js, test/get-core/edges.spec.js, test/integration/call.spec.js
Up until this PR, Falcor would not notify if none of the requested values were found in the DataSource. Consequently in some circumstances onNext would not fire. This was unergonomic as this unpredictability forced developers to register an onCompleted handler in addition to the onNext if they wanted to perform clean up tasks. It also meant that sometimes Promises never resolved. 
With this PR, Falcor will onNext even if none of the requested values exist in the DataSource. In progressive mode, it will continue to onNext immediately if at least one of the requested values is present in the cache. However this PR will also cause it to onNext if any requested value is **known to be undefined** (i.e. an atom of undefined is used to store this info in the cache). 
In other words it is now …
=> Always onNext if any value discovered in cache

lib/request/GetRequestV2.js, lib/response/get/getRequestCycle.js, test/falcor/error/index.js, test/falcor/get/get.cacheAsDataSource.spec.js, test/falcor/get/get.dataSource-only.spec.js, test/lru/lru.splice.expired.spec.js
**BREAKING CHANGE**: Model no longer creates path-bound errors when DataSource onErrors
In the current Master HEAD if a DataSource's Observable onError's, the Falcor Model will create a path-bound error for every requested path, and insert a JSON Graph error object at each requested path in the Model cache. **The problem with this approach to error handling is that it can create the false impression that objects exist which do not exist.**
As an example, the code below attempts to retrieve two paths from a DataSource which always onErrors.
```js
import { Observable } from "rx"
const FailingDataSource = { 
get() { return Observable.error({ message: "FAIL" }); }
};
async function test() {
const model = new falcor.Model({ source: FailingDataSource }):
try {
await model.get(["videos", …
```
=> No longer creating Path-bound errors for DataSource errors

lib/deref/sync.js
This is the same case as Model.get, so boundPath and shortedPath are both set to path.
=> Log the path when throwing InvalidModelError.

.gitignore, lib/get/onValue.js, test/get-core/references.spec.js, test/get-core/values.spec.js, test/getCoreRunner.js
Previously, model.get(['a', 'b']) where b is a reference would result in references in the json output. This change instead results in emitting nothing where a reference would previously exist. JSONG remains unchanged.
=> Omit references

lib/get/get.js, lib/get/onValue.js, lib/get/onValueType.js, lib/get/util/clone.js, lib/get/walkPath.js, lib/response/get/GetResponse.js, lib/response/get/checkCacheAndReport.js, lib/response/get/getRequestCycle.js, lib/response/set/setRequestCycle.js, lib/support/mergeJSONGraphNode.js, test/falcor/deref/deref.errors.spec.js, test/falcor/error/index.js, test/falcor/get/get.cache-only.spec.js, test/falcor/get/get.cacheAsDataSource.spec.js, test/falcor/get/get.dataSource-and-cache.spec.js, test/falcor/invalidate/invalidate.cache-only.spec.js, test/falcor/set/set.cacheAsDataSource-and-cache.spec.js, test/falcor/set/set.dataSource-and-cache.spec.js, test/falcor/set/set.setCache.spec.js, test/get-core/deref.spec.js, test/get-core/edges.spec.js, test/get-core/errors.spec.js, test/get-core/missing.spec.js, test/get-core/values.spec.js, test/getCoreRunner.js, test/integration/call.spec.js, test/internal/request/RequestQueue.get.spec.js, test/lru/lru.splice.expired.spec.js
Currently, a get() for paths that are missing in the cache behaves differently than a get() for atoms of undefined. This PR makes both conditions produce identical results, and ensures onNext() is always called on the model result.
=> Always onnext

lib/get/get.js, lib/invalidate/invalidatePathSets.js, lib/request/GetRequestV2.js, lib/request/RequestQueueV2.js, lib/response/get/getRequestCycle.js, lib/set/setJSONGraphs.js, lib/set/setPathValues.js, lib/support/mergeJSONGraphNode.js, lib/support/mergeValueOrInsertBranch.js, lib/support/removeNodeAndDescendants.js, lib/support/replaceNode.js, test/falcor/get/get.dataSource-and-cache.spec.js
The scenario which exposed this bug was receiving an error for some set of paths (likely due to loss of connection), merging a mix of errors and atoms with varying expiry, then successfully retrying a set of expired paths sharing the structure with non-expired paths. Explicit invalidation serves the same purpose as differing expiry, however.
The root cause was the mutable nature of pending json output, coupled with not blacklisting the $__path property. If something that was previously at a deep branch structure [lolomo, 0, 0, item, title] and expired/was invalidated resulting in a datasource request, upon merging into the output json the $__path field (which is an alias for $_absolutePath on cache nodes) would be partially overwritten, resulting in corrupted paths.
The solution was to …
=> Fix merging references over branches

lib/ModelDataSourceAdapter.js, test/falcor/get/get.model.adapter.spec.js, test/falcor/get/index.js
toDataSource should use _jsonGraph() as output which properly does boxValues when needed.
=> 0.x change for removing boxValues from asDataSource().

package.json
As it is removed in v1.0.0 and only being used in test.
=> Move rx to devDependencies

lib/errors/MaxRetryExceededError.js, lib/response/get/getRequestCycle.js, lib/response/set/setRequestCycle.js, package.json, test/falcor/get/get.dataSource-only.spec.js, test/falcor/set/set.dataSource-only.spec.js
this will help developers understand data source and service failures better
=> Include missing paths in MaxRetryExceededError instances

.eslintrc, lib/get/onMissing.js, lib/request/GetRequestV2.js, lib/request/RequestQueueV2.js, lib/request/complement.js, lib/response/get/checkCacheAndReport.js, lib/response/get/getRequestCycle.js, package-lock.json, package.json, test/data/LocalDataSource.js, test/integration/dedupe.spec.js, test/integration/get.spec.js, test/integration/index.js, test/internal/request/GetRequest.add.spec.js, test/internal/request/RequestQueue.get.spec.js
update:
pull request is ready for review and merging! all edge cases covered.
update:
pull request is up for review now. all edge case bugs fixed. adding some tests now.
dedupes 2 major cases: paths followed via refs in cache, and paths with ranges in the end
pull request is still in progress, but still want to get opinion on the approach
work remaining: dedupe paths with more properties after the range, and not followed via refs in client cache (like `['videosById', { from: 0, to: 10 }, 'name' ]` where `videosById` is not in cache
fixes #779
=> partial request deduping

lib/Model.js, test/invalidate/index.js
from blowing away the entire cache
=> protect against model.invalidate(undefined) and model.invalidate([])

lib/Model.js, test/Model.spec.js
https://github.com/Netflix/falcor/issues/915
No clue if you guys take pull requests but this appears to fix the issue above.
For ease of reading at a glance I will reiterate what this is fixing. batch calls this._clone, _clone instantiates Model with `this`, the instance of the model does not have a property maxRetries but rather _maxRetries, therefore maxRetries gets reset to the default if you do the following
`new falcor.Model({maxRetries: 10, ... }).batch(...)`
Also I can write a test for this if you'd like
=> Fix max retries on clone

lib/Model.js, lib/request/GetRequestV2.js, lib/support/mergeJSONGraphNode.js, test/falcor/get/get.dataSource-only.spec.js, test/set/edge-cases.spec.js
This PR accomplishes two things:
It fixes a bug where whole branches were merged from jsonGraph responses, leading to nodes to be merged without also receiving their metadata such as $_absolutePath.
Adds a (for now) private model flag, _useServerPaths which can enable folks to opt into response stuffing. I opted for a private flag for now as I see this as a pretty major foot gun.
=> Response stuffing

_includes/homepage-getting-started.md
Adds a line in `index.js` for serving static files from current directory so reader can visit `localhost:3000/index.html` in the next step.
Assuming this is the right file to update code sample at https://netflix.github.io/falcor/
=> Update homepage-getting-started.md to match README

.travis.yml, lib/Model.js, test/Model.spec.js
Due to incorrect reference to internal property of _maxRetries when
cloning a Falcor model instance, which occurs internally when enabling
batching, maxRetries always gets reset when enabling batching.
Originally fixed in PR #917
=> Issue #915 reintroduced in v2 of Falcor

lib/Model.js
If I subclass `Model` like so:
``` js
class MyModel extends Model { ... }
var model = new MyModel().batch();
```
`batch()` nevertheless returns an instance of `Model`. This PR makes it so `batch()` and other cloning methods would return instances of `MyModel`.
=> Make Model#_clone return instance of current type

test/Model.spec.js
adds tests for #730 
thanks @greim!
=> Make Model#_clone() return the right sub-typed class, instead of Model

README.md
the example code had a syntax error due to an errant semicolon inside of an object literal
=> fix minor syntax error in README.md

lib/get/onValue.js, test/get-core/values.spec.js
In the onNext consistency fix, a null check was omitted which caused `onValue` to fail to handle outerValues being unset. This situation only occurs in JSONG mode when a ref to a ref is followed from `followReference`, which was not covered by a code test.
This PR adds a code test for that scenario, and pulls in the fix from #930.
=> Fixing double ref JSONG issue

lib/response/get/GetResponse.js, lib/response/set/SetResponse.js
**Case in Point**
Using `falcor@^2.0.6` with Angular 6 with Typescript 2.9.2 when generating source maps fails with this message from Typescript transpilation: `Error: Debug Failure. False expression.`
**Issues fixed**
Because of the `a = b = c` structure used below (in `GetResponse.js` and `SetResponse.js`):
`var GetResponse = module.exports = function GetResponse(model, paths ...`
This triggers the following github issue: https://github.com/Microsoft/TypeScript/issues/24963.
As we are using Angular 6, it is undesirable to change Typescript versions, so i'm fixing the problem at the source.  There are other areas where this pattern exists in the **falcor** codebase, but this is the minimal change to solve our immediate issue.  Happy to update the other files if it's a requirement.
I have …
=> fix: typescript transpilation / assertion error in 2.9.x

lib/Model.js, lib/request/GetRequestV2.js, lib/request/RequestQueueV2.js, lib/request/flushGetRequest.js, test/Model.spec.js, test/internal/request/RequestQueue.get.spec.js, test/invalidate/index.js, test/set/index.js
Added flags to disable request deduplication and path collapsing. These are expensive algorithms and we'd like to quantify their impact on users.
=> Add flags for expensive path algorithms

lib/get/onValue.js, lib/get/walkPath.js, test/falcor/get/get.cache-only.spec.js
When calling `Model.get()` with overlapping path sets where a subsequent path set contains an empty key set, some values in the result are lost. This has been fixed by not overwriting an existing result node.
=> Empty keyset bug

lib/get/walkPath.js, test/get-core/null.spec.js
As the title says. Throwing has proven to be of limited value, and is causing log spam and unhandled Promise rejections.
=> Skip nulls in path instead of throwing

.github/workflows/ci.yml
Adds a GitHub Actions workflow to [build and test Node.js](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs) based on the [current TravisCI configuration](https://github.com/Netflix/falcor/blob/master/.travis.yml).
=> Enable GitHub Actions for CI

lib/get/walkPath.js, test/get-core/edges.spec.js
Missing paths were generated by the recent change to paths with null/undefined/empty key sets. This resulted in unnecessary network requests.
=> Avoid fetching null paths
