Netflix/falcor

package.json

Per https://spdx.org/licenses/

Set package.json license to valid SPDX string

---

_data/navigation.yml
starter/why-falcor.md

Add 'Why Falcor?' video page to the introduction section

---

.travis.yml

Also, should the travis build be moved over from magnum to the docker version for open source projects?

Run travis builds as a docker container

---

README.md

Fix the falcor-hapi link

---

documentation/paths.md

I don't know if the API has changed, if it is a bug or a typo but this modified example works.

fix doc examples

---

lib/get/util/lru.js
test/lru/lru.promote.get.spec.js
test/lru/lru.promote.set.spec.js
test/lru/lru.splice.expired.spec.js
test/lru/lru.splice.overwrite.spec.js

I updated the LRU unit tests to be more specific.  They are easier to debug.  Could help when looking at cache collect @sdesai

Lru unit tests

---

lib/response/get/GetResponse.js
test/falcor/get/get.cache-only.spec.js

GetResponse did not have the .then function.

---

test/get-core/deref.spec.js
test/get-core/edges.spec.js
test/get-core/errors.spec.js
test/get-core/index.js
test/get-core/missing.spec.js
test/get-core/references.spec.js
test/get-core/values.spec.js
test/getCoreRunner.js

@sdesai This should be obvious that this is just a simple way to be more explicit with get tests.  I thought the other way may be easier to debug, but it was not.  This should be the right balance of debugability of get core and explicitness.

Better core get

---

lib/Model.js
lib/response/CallResponse.js
test/falcor/call/call.spec.js
test/falcor/error/index.js

Now call responses are simple since they only need to forward the request to the source.  If the source does not exist then we will observer.onError function does not exist.

No more local function calls and rewrote CallResponse to be more simple.

---

build/deploy-ghpages.sh

1. Get off detached head, and onto the branch we're building (master in this case, but driven by $TRAVIS_BRANCH)
2. Add a new remote, same repo we're in, but using a url format Travis can push to.

Try committing the dist, one more time

---

build/gulp-build.js
lib/response/CallResponse.js

fix lint errors and add the lint task into build process.

---

lib/set/setJSONGraphs.js
lib/set/setPathMaps.js
lib/set/setPathValues.js

Small fixes to docs on internal set methods.

---

lib/response/IdempotentResponse.js
lib/response/get/getRequestCycle.js
test/falcor/get/get.dataSource-and-cache.spec.js

Pass the cache root's version to LRU collect after the get and set operations have finished mutating the cache. Fixes #507. cc: @michaelbpaulson @sdesai @jhusain

Actually GC cache items when we collect the LRU.

---

lib/get/walkPath.js
test/lru/lru.promote.get.spec.js

found that references were not being promoted.

---

documentation/datasources.md
documentation/jsongraph.md
documentation/router.md

While working through the documentation, found some inconsistencies. A couple incorrect responses in comments, and incorrect variable name and made a grammatical fix.

Read thru doc fixes

---

lib/get/getCache.js
lib/support/isInternalKey.js

`git cherry-pick 5987a2cfe9092b19cb0ff37a34c21605d9971029`ed out this change from 0.x

The merge from 0.x branch for removing the potential for infinite recursion on getCache.

---

lib/ModelRoot.js
test/internal/ModelRoot.comparator.spec.js
test/internal/index.js

@sdesai this is for internal need.  I'll cherry-pick this commit along with #639 shortly.

Comparator upgrades to have more fine grain comparison

---

documentation/router.md

https://github.com/Netflix/falcor/issues/648

Fixed a minor mistake in docs (#648)

---

lib/deref/index.js
test/falcor/bind/bind-cases.spec.js

Addresses #669 
@sdesai do you want to take a look at this?  If not I can merge it and move on.

fixes #669 of old deref not working when the leaf paths are all {$type: atom}s.

---

lib/set/setPathValues.js
lib/support/mergeJSONGraphNode.js

since get is used during a set, there is no need for set to promote.

feat(perf): There is a big performance win removing promote from set.

---

documentation/router.md

Fix for incorrect code in the router docs.

router.md: change 'keys' to 'props'

---

lib/Model.js
lib/get/onValue.js
lib/set/setJSONGraphs.js
lib/set/setPathMaps.js
lib/set/setPathValues.js
lib/support/mergeJSONGraphNode.js
performance/tests/get/get.perf.js
performance/tests/standard.js
test/falcor/set/set.setCache.spec.js

There is definitely a performance win here.  When the extra promotes
are removed both flamegraphs and benchmarksjs show a difference.

feat(performance): The removal of extra LRU promotes.

---

lib/deref/index.js
lib/deref/sync.js
test/falcor/bind/bind-cases.spec.js
test/falcor/bind/bind.short.spec.js

This way the cache is in a cleaner state.

Redid deref on 0.x so that it performs the get first to avoid issues.

---

lib/deref/index.js
lib/get/getValueSync.js
test/falcor/bind/bind-cases.spec.js

I went back to the _old deref_ and found some of the issues that were affecting the window's team.  I doubt I have all the cases covered, but we are more covered. 
Why did you go back to the old deref again?  It turns out the way I was trying to do this was preventing some behavior that was very nuanced...

found some of the issues that could be plaguing deref.

---

lib/response/get/checkCacheAndReport.js
test/data/LocalDataSource.js
test/falcor/error/index.js
test/falcor/get/get.dataSource-and-cache.spec.js

Fixes: https://github.com/Netflix/falcor/issues/678

Fix materialized issue

---

lib/Model.js

Fixed spelling on line 281

---

.editorconfig

to ensure correct spaces are used ;)

feat: editorconfig

---

lib/response/ModelResponse.js
test/falcor/call/call.spec.js

Fixes https://github.com/Netflix/falcor/issues/728
Tried to capture it with a test case. It failed before making the fix, now it passes. Thanks!
@michaelbpaulson

Don't re-execute a call on multiple then()s.

---

examples/datasource/webWorkerSource.js

Updates webWorkerSource example:
* Use Rx instead of the previously included version of Rx attached to falcor
* Use the correct to JSONG function
* Add additional clarifying comments
This fixes #727

Update webWorkerSource to work with the the newest falcor

---

lib/get/onMissing.js
lib/response/get/checkCacheAndReport.js
test/falcor/get/get.dataSource-and-cache.spec.js

When a path was missing from the cache, but is terminated before the
empty path, it would be added to the missing path list.

fix(empty-path): Fixed an empty path on empty cache issue.

---

package.json

Lock bootstrap dependency version

---

.gitignore
build/deploy-ghpages.sh

Cherry-pick the relevant commit from master to commit docs to 0.x branch.

Commit docs to branch on developer site build

---

.travis.yml

We may also want to remove 0.10 and add 5.

Run Travis tests against Node 4.

---

doc/Model.html
doc/Model.js.html
lib/Model.js

Open to suggestions for how to explain this :)
Props to @trxcllnt for the explanation.
Closes #770

Add docs for what maxSize represents

---

lib/get/get.js
test/falcor/get/get.dataSource-and-bind.spec.js

Replaces #810 - omits dist changes for merging.

Deref purged fix

---

documentation/router.md

- adds `.prototype` to fix Object instantiation. https://github.com/Netflix/falcor/compare/gh-pages...stevelacy:gh-pages?expand=1#diff-baef559ba7d4197065edabd0af8baae0R348
- removes trailing whitespace

Fix documentation for Authorization

---

documentation/router.md

fixes #899: incorrect js sample for inheriting from BaseRouter

---

lib/Model.js
lib/get/onValue.js
package.json
test/get-core/values.spec.js
test/getCoreRunner.js

Note for observers: this is a private, _temporary_ change to accommodate an internal need at Netflix, and this behavior will not be ported to 2.x+.

Adds reference emission flag

---

lib/Model.js
lib/get/getVersion.js
lib/get/sync.js

fix _getValueSync

---

documentation/model.md

"inefficient" instead of "inefficent".

Typo fix in doc
